services:
  - type: web
    name: smart-attendance-cv-service
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
